language: csharp
solution: src/Labwork2/lab2.sln
install:
  - nuget restore src/Labwork2/lab2.sln
  - nuget install NUnit.Runners -Version 3.7.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release src/Labwork2/lab2.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe src/Labwork2/UnitTestLab2/bin/Release/UnitTestLab2.dll